# -----------------------------------------------------------------------------------------------------------
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# -----------------------------------------------------------------------------------------------------------

"""input_gen.py — FUSED template (multi-tensor with shape_derive, rank 2-4).

Emitted by /aog-input-gen-builder for ops with multiple tensors whose shapes relate
to a base_shape via broadcasts or dim reductions. Examples:
  - op#6 MoeFinalizeRouting: 7 tensors with shapes [N*K,H]/[N,H]/[E,H]/[N,K]...
  - op#11 DequantSwigluQuant: 4 tensors with [N,2H]/[1,2H]/[N,1]/[1,H]
  - op#24 KvCacheUpdateWithRopeBackward: 4 tensors rank-4 with grad/cos-sin/cache_position

Template filling guide:

Per-tensor shape functions receive the base shape. A routing operator can use
helpers equivalent to these:

    _epr_shape = lambda shape: [shape[0] * K_DEFAULT, shape[1]]
    _row2_shape = lambda shape: list(shape)
    _bias_shape = lambda shape: [E_DEFAULT, shape[1]]

Index or permutation inputs may use a custom value generator:

    def _s2d_gen(size, dtype, seed):
        generator = torch.Generator().manual_seed(seed + 42)
        return torch.randperm(size, generator=generator).to(torch.int32)

A filled tensor and scalar contract can contain entries such as:

    "tensor_inputs": [
        {"name": "x", "role": "operand"},
        {"name": "weights", "role": "operand",
         "shape_derive": lambda shape: [1, shape[-1]]},
        {"name": "indices", "role": "index", "dtype": torch.int32,
         "shape_derive": lambda shape: [shape[0] * 2],
         "invariant": "permutation"},
        {"name": "expert_for_row", "role": "index", "dtype": torch.int32,
         "shape_derive": lambda shape: [shape[0], K_DEFAULT],
         "invariant": "index_range:E_DEFAULT"},
    ],
    "scalar_inputs": [
        {"name": "drop_pad_mode", "dtype": "int", "default": 0,
         "probe_values": [0, 1, 2, 3]},
    ],

The optional op_class field enables domain-semantic shape bands generated by
case_gen. Registered attention classes are attention and fa_class; they add
rank-four batch, sequence, head, and head-dimension bands including dimensions
640 and 768. When enabling it with an entry such as
"op_class": "attention", the base-shape filter must retain those bands. Declare
relevant scalars, such as keep_prob, so case_gen can combine shape and config
coverage. Omit op_class when no domain emitter is registered.
"""
from __future__ import annotations
import json
import pathlib
import sys
import torch

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "src" / "scripts" / "reference_provider"))
from case_gen import dataset_data_sha256, generate_cases, case_data_sha256  # noqa: E402


def _stringify_tensor_stat(t):
    """Bug B (blue 2026-06-01): manifest cases[].input_stats must match the
    canonical input_gen.template.py schema so the reference provider's
    kwargs_from_workspace_manifest_case0 can build real-shape probe inputs.
    Mirrors input_gen.template.py:_stringify_tensor_stat."""
    if isinstance(t, torch.Tensor):
        return {"min": float(t.min()), "max": float(t.max()),
                "mean": float(t.mean()) if t.dtype.is_floating_point else None,
                "std": float(t.std()) if t.dtype.is_floating_point and t.numel() > 1 else None,
                "shape": list(t.shape), "dtype": str(t.dtype).replace("torch.", "")}
    return {"value": t}


def _identity_shape(base):
    """Use the base shape unchanged for one tensor input."""
    return list(base)


def _base_shape_valid(base):
    """Reject base_shapes that don't match this op's rank/alignment."""
    return len(base) == int("<<<RANK>>>") and all(d >= 1 for d in base)


SCHEMA = {
    "op_name": "<<<OP_NAME>>>",
    "formula": "<<<FORMULA>>>",
    "tensor_inputs": [],
    "scalar_inputs": [],
    "tensor_output": "<<<OUTPUT_NAME>>>",
    "rank": int("<<<RANK>>>"),
    "base_shape_filter": _base_shape_valid,
}

COVERAGE_TIER = "<<<COVERAGE_TIER>>>"
DTYPE = getattr(torch, "<<<DTYPE>>>".rsplit(".", 1)[-1])   # torch.float32 or float32


def main():
    out_dir = pathlib.Path(__file__).parent

    if "<<<" in str(SCHEMA) or "<<<" in COVERAGE_TIER:
        raise RuntimeError(
            "input_gen.py has unfilled <<<>>> placeholders — /aog-input-gen-builder "
            "skill should have filled these. If running standalone, fill manually."
        )

    cases = generate_cases(SCHEMA, coverage_tier=COVERAGE_TIER, dtype=DTYPE)

    payload = {
        "op": SCHEMA["op_name"],
        "formula": SCHEMA["formula"],
        "dtype": str(DTYPE).replace("torch.", ""),
        "coverage_tier": COVERAGE_TIER,
        "schema": _schema_to_json(SCHEMA),
        "cases": cases,
        "data_sha256": dataset_data_sha256(cases),
    }
    torch.save(payload, out_dir / "edge_inputs.pt")

    manifest = {
        "op": SCHEMA["op_name"],
        "formula": SCHEMA["formula"],
        "dtype": str(DTYPE).replace("torch.", ""),
        "coverage_tier": COVERAGE_TIER,
        "n_cases": len(cases),
        "data_sha256": payload["data_sha256"],
        # Bug B (blue 2026-06-01): full per-case dict with input_stats (NOT just
        # string names) so downstream reference runners can
        # build real-shape probe inputs. Matches input_gen.template.py:292-298.
        "cases": [
            {"idx": c.get("idx", i), "name": c.get("name", f"case_{i}"),
             "shape": c.get("shape"),
             "input_sha256": case_data_sha256(c),
             "input_stats": {k: _stringify_tensor_stat(v) for k, v in c["inputs"].items()},
             "meta": c.get("meta", {})}
            for i, c in enumerate(cases)
        ],
    }
    (out_dir / "manifest.json").write_text(json.dumps(manifest, indent=2))
    print(f"wrote edge_inputs.pt ({len(cases)} cases) + manifest.json")


def _schema_to_json(schema):
    out = {k: v for k, v in schema.items() if not callable(v)}
    if "tensor_inputs" in out:
        out["tensor_inputs"] = [
            {k: (str(v) if isinstance(v, torch.dtype) else v) for k, v in t.items() if not callable(v)}
            for t in schema["tensor_inputs"]
        ]
    if "scalar_inputs" in out:
        out["scalar_inputs"] = [
            {k: v for k, v in s.items() if not callable(v)}
            for s in schema["scalar_inputs"]
        ]
    return out


if __name__ == "__main__":
    main()
