/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

// ============================================================================
// a3 MIX_AIC_1_2 cross-core SYNC-WITNESS — pybind entry (handshake only).
//
// Pybind purity: metadata + alloc + contiguous only; ALL device work (2 genuine
// cube matmuls + the placeholder identity copy) is in the AscendC kernel. No
// torch math ops here.
//
// This shim launches a WITNESS, not an operator. It ACCEPTS ONE FIXED SHAPE
// (seq=128, d=64, fp16, one head, one batch) and hard-rejects everything else.
// The device compute between the flags is a TRIVIAL PLACEHOLDER — there is
// nothing here to copy for a real op. Witness the MIX handshake close, then
// WRITE YOUR OWN kernel for your target op (the DEBT-215 scanner flags verbatim
// imports of teaching references).
// ============================================================================
#include <pybind11/pybind11.h>
#include <torch/extension.h>
#include <torch_npu/csrc/core/npu/NPUStream.h>
#include <cmath>
#include <cstdint>

// The fixed teaching shape. Not a tunable — changing it is "write your own".
constexpr int64_t EXAMPLE_SEQ = 128;
constexpr int64_t EXAMPLE_D   = 64;

// C-linkage launch shim auto-generated by ascendc.cmake from the __global__ entry.
extern "C" uint32_t aclrtlaunch_mix_fa_min_example_fp16(
    uint32_t blockDim, void* stream,
    void* q, void* k, void* v, void* o,
    void* s_gm, void* p_gm,
    int32_t seq, int32_t d);

// SYNC-WITNESS (single fixed shape): O = (Q @ K^T) @ V with the AIV step a
// PLACEHOLDER identity copy (P = S) — NOT softmax, NOT a real FA op.
//   Q,K,V : [128, 64] fp16 (one head, one batch).  Returns O : [128, 64] fp16.
torch::Tensor run_example(torch::Tensor Q, torch::Tensor K, torch::Tensor V) {
    TORCH_CHECK(Q.device().type() == c10::DeviceType::PrivateUse1, "Q must be on NPU");
    TORCH_CHECK(K.device().type() == c10::DeviceType::PrivateUse1, "K must be on NPU");
    TORCH_CHECK(V.device().type() == c10::DeviceType::PrivateUse1, "V must be on NPU");
    TORCH_CHECK(Q.dim() == 2 && K.dim() == 2 && V.dim() == 2, "Q,K,V must be 2D");
    TORCH_CHECK(Q.dtype() == torch::kFloat16 && K.dtype() == torch::kFloat16 &&
                V.dtype() == torch::kFloat16, "fp16 only for this example");

    auto Qc = Q.contiguous();
    auto Kc = K.contiguous();
    auto Vc = V.contiguous();

    // Structural teaching-scope guard: this example is the ONE fixed shape only.
    TORCH_CHECK(Qc.size(0) == EXAMPLE_SEQ && Qc.size(1) == EXAMPLE_D,
                "this is a minimal teaching example fixed at seq=128,d=64 — "
                "write your own kernel for other shapes");
    TORCH_CHECK(Kc.size(0) == EXAMPLE_SEQ && Kc.size(1) == EXAMPLE_D, "K must be [128,64]");
    TORCH_CHECK(Vc.size(0) == EXAMPLE_SEQ && Vc.size(1) == EXAMPLE_D, "V must be [128,64]");

    const int32_t seq = static_cast<int32_t>(EXAMPLE_SEQ);
    const int32_t d   = static_cast<int32_t>(EXAMPLE_D);

    auto out  = torch::empty({EXAMPLE_SEQ, EXAMPLE_D},  Qc.options());  // O [seq,d]
    auto sMat = torch::empty({EXAMPLE_SEQ, EXAMPLE_SEQ}, Qc.options()); // S [seq,seq] scratch
    auto pMat = torch::empty({EXAMPLE_SEQ, EXAMPLE_SEQ}, Qc.options()); // P [seq,seq] scratch

    auto stream = c10_npu::getCurrentNPUStream().stream();
    uint32_t blockDim = 1;  // 1 AIC block; runtime pairs the AIV(s) for MIX.

    uint32_t ret = aclrtlaunch_mix_fa_min_example_fp16(blockDim, stream,
        Qc.data_ptr(), Kc.data_ptr(), Vc.data_ptr(), out.data_ptr(),
        sMat.data_ptr(), pMat.data_ptr(), seq, d);
    TORCH_CHECK(ret == 0, "mix_fa_min sync-witness kernel launch failed, error=", ret);
    return out;
}

PYBIND11_MODULE(_a3_mix_fa_min_example, m) {
    m.def("run_example", &run_example,
          "a3 MIX_AIC_1_2 cross-core SYNC-WITNESS (fixed seq=128,d=64) — "
          "build/run to witness the AIC<->AIV handshake close deadlock-free; "
          "compute is a placeholder, write your own kernel for a real op",
          pybind11::arg("Q"), pybind11::arg("K"), pybind11::arg("V"));
}
