[pytest]
testpaths = agent/example/testcases
pythonpath = . agent/example
markers =
    easyasc_device(device): run this test with a specific EasyASC device baseline ("b3"/"a2", "a3"/"910c"/"9362", "950"/"a5", or "950pr"/"a5pr")
