# ----------------------------------------------------------------------------------------------------------
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software; you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# ----------------------------------------------------------------------------------------------------------
"""Phase O2.5 A3-CANN reference — provisioning support + remote exec (decomposed 2026-07-06).

Cohesive LEAF: the A3 remote-exec transport (default run_remote, reachability
probe, scp push/pull), the pre-generation gates/scaffolds (prior-art scan,
source-arch completeness, CPU-truth scaffold), the A3 kernel build + reference
run, the aog-a3-author fallback, and the block-message formatter. The top-level
orchestration entry `provision_a3_reference` remains in the phase_o25_a3_ref
facade and calls these by name (re-imported there). This leaf imports stdlib +
shared helpers from a3_ref_common / a3_ref_npu / a3_ref_validate; it NEVER
imports from the phase_o25_a3_ref facade (unidirectional edge, no cycle).

NOTE (coupling): run_a3_reference resolves its scp defaults (_scp_push_dir /
_scp_pull_files) from THIS module's namespace. Tests that exercise the
probe_only=False path patch them here (a3_ref_provision._scp_push_dir), not on
the facade.
"""
from __future__ import annotations
import logging

import json
import os
import re
import shlex
import subprocess
from pathlib import Path
from typing import Callable, Optional

from a3_ref_common import (
    O25A3Report,
    RunRemote,
    _a3_container_home,
    log,
)
from source_arch import detect_source_arch
from source_op import resolve_logical_op_name
from a3_ref_npu import _a3_host_workspace_root_from_env
from a3_ref_validate import provision_cpu_truth, provision_native_capture


_RUNNER_FAILURE_MARKERS = (
    "notimplementederror",
    "could not find an implementation",
    "could not run",
    "undefined symbol",
    "561103",
    "no binary",
    "kernel not registered",
    "kernel-not-registered",
    "aclnn",
)


_CPU_TRUTH_TEMPLATE = (
    "# CPU truth template — `{op}`\n\n"
    "Phase A.5 deliverable (after analysis.md, before file mirror).\n\n"
    "**Purpose**: when port_a3_to_a5 uses A3-NPU-output as reference,\n"
    "without an independent ground truth we cannot detect upstream-CANN\n"
    "kernel bugs. CPU fp64 implementation of the published algorithm\n"
    "spec gives that ground truth: A5 vs A3 = port alignment, A5 vs CPU\n"
    "= algorithmic correctness, divergence → upstream bug escalation.\n\n"
    "## Expected output\n\n"
    "`workspace/{op}/cpu_truth_reference.py` — pure-Python fp64\n"
    "implementation of the algorithm. Same input/output schema as the\n"
    "A3 source kernel. CLI: `python3 cpu_truth_reference.py [--case ID]\n"
    "[--compare a3|a5|both]`. Writes `cpu_truth_outputs.pt` and\n"
    "`cpu_truth_compare.json`.\n\n"
    "**NOTE (owner 2026-06-30, ② native_capture):** `native_capture.pt` (the CPU-same-precision\n"
    "baseline the 生态 compare.py grader needs for its small-value carve-out) is now\n"
    "PROVIDER-AUTO-GENERATED by the harness (`phase_o25_a3_ref.provision_native_capture` runs\n"
    "model.py.Model.forward @ native dtype over edge_inputs.pt — O2.5 Step 0.8). You do NOT\n"
    "need to emit it. (If your oracle also writes it — same math at native dtype, NOT a cast of\n"
    "the fp64 output — that is a harmless belt; the harness's auto-gen is authoritative.)\n\n"
    "{schema_block}"
    "## Authoring basis\n\n"
    "Implement the published algorithm from this operator's arch22 source\n"
    "and declared interface. Provenance-tracked prior art or a target archive\n"
    "may be consulted for migration research; record every consulted path in\n"
    "reference_manifest.jsonl. Live arch22 capture remains the migration truth.\n\n"
    "## When supplemental CPU truth is not authoritative\n\n"
    "- L2/L3 ops where algorithm semantics are hardware-defined (cube\n"
    "  MatmulImpl, fp8/bf16 hardware accumulation) may document that a\n"
    "  pure-Python oracle cannot faithfully model dtype behavior. This\n"
    "  never waives the mandatory live arch22 capture or target verify.\n\n"
    "## When to insist\n\n"
    "- Numerical-algorithm ops (norm + quant, adam variants, sort/topk,\n"
    "  reductions, foreach unary/binary). Pure-Python fp64 captures\n"
    "  semantics; non-trivial to model dtypes is acceptable here.\n\n"
    "Build CPU truth then `python3 cpu_truth_reference.py --compare a3`\n"
    "to validate A3 reference. If A3 vs CPU max_abs_err > T2 tolerance\n"
    "→ upstream bug, escalate to PARTIAL_PERSIST + upstream filing.\n"
    "If A3 vs CPU passes → A3 is correct ground truth, proceed normally.\n"
)


def _bounded_runner_failure(exec_log: str) -> str:
    """Return a bounded, redacted failure excerpt without losing the first cause.

    A per-case runner can emit hundreds of repeated failures.  Keeping only its
    final bytes hid the first dispatch error (notably ``561103``) behind the
    capture summary, so the source-build fallback never ran.  Preserve at most
    eight narrowly matched diagnostic lines plus a short tail.
    """
    redacted = re.sub(
        r"(?i)\b(?:ANTHROPIC_API_KEY|DEEPSEEK_API_KEY|OPENAI_API_KEY)"
        r"\s*[:=]\s*[^\s]+",
        "API_KEY=<redacted>",
        exec_log,
    )
    redacted = re.sub(r"\bsk-[A-Za-z0-9_-]{8,}\b", "sk-<redacted>", redacted)
    lines = redacted.splitlines()
    signatures = [
        line[:500]
        for line in lines
        if any(marker in line.casefold() for marker in _RUNNER_FAILURE_MARKERS)
    ][:8]
    tail = "\n".join(lines[-12:])[-1200:]
    parts: list[str] = []
    if signatures:
        parts.append("failure signatures:\n" + "\n".join(signatures))
    if tail:
        parts.append("log tail:\n" + tail)
    excerpt = "\n".join(parts) or "<no runner output>"
    return excerpt[:4000]


def _default_run_remote(env_a3_user: str, env_a3_host: str, env_a3_container: str) -> RunRemote:
    """Build a run_remote callable that ssh-es to A3 host + docker exec into
    the A3 container.

    Tests inject their own run_remote that returns canned (rc, out, err)
    tuples. Production code uses this default which does the real ssh +
    docker exec.

    A3_HOST_MODE (2026-06-11): when the A3 host runs torch_npu HOST-DIRECT (no
    npu-a3 container with torch, e.g. 97-73 where the container's python lacks
    torch but /root/miniconda3 has torch_npu 2.9 + npu_fusion_attention), set
    A3_HOST_MODE=1 + A3_NPU_PYTHON_BIN=<dir>. The wrapper then ssh-es WITHOUT
    docker exec and prepends A3_NPU_PYTHON_BIN to PATH so inline `python3`
    resolves to the torch_npu interpreter. Mirrors the A5_HOST_MODE pattern.
    """
    host_mode = str(os.environ.get("A3_HOST_MODE", "")) == "1"
    npu_py_bin = str(os.environ.get("A3_NPU_PYTHON_BIN", "")).rstrip("/")

    def run(cmd: str) -> tuple[int, str, str]:
        if host_mode:
            # host-direct: no docker exec; prepend torch_npu python bin to PATH
            inner = f"export PATH={npu_py_bin}:$PATH; {cmd}" if npu_py_bin else cmd
            remote = f"bash -lc {shlex.quote(inner)}"
        else:
            remote = f"docker exec {env_a3_container} bash -lc {shlex.quote(cmd)}"
            # Optional sudo-gated docker host (A3_DOCKER_SUDO / A5_DOCKER_SUDO): some shared
            # A5/A3 boxes give the ssh user NOPASSWD only for `sudo su` (not `sudo docker`).
            # Wrap the whole docker command as `sudo su -c <quoted>` when the flag is set.
            # Default OFF → byte-identical to prior behavior. shlex.quote keeps the nesting robust.
            if (
                str(
                    os.environ.get("A3_DOCKER_SUDO", os.environ.get("A5_DOCKER_SUDO", ""))
                ).strip().lower()
                in ("1", "true", "yes", "on")
            ):
                remote = f"sudo su -c {shlex.quote(remote)}"
        ssh_cmd = [
            "ssh",
            "-o", "StrictHostKeyChecking=no",
            "-o", "UserKnownHostsFile=/dev/null",
            "-o", "ConnectTimeout=10",
            f"{env_a3_user}@{env_a3_host}",
            remote,
        ]
        try:
            result = subprocess.run(
                ssh_cmd, capture_output=True, text=True, timeout=600,
            )
            return result.returncode, result.stdout, result.stderr
        except subprocess.TimeoutExpired:
            return 124, "", "TimeoutExpired: command exceeded 600s"
        except Exception as e:
            return 1, "", f"subprocess error: {e!r}"
    return run


def probe_a3_reachable(
    env_a3_user: str,
    env_a3_host: str,
    env_a3_container: str,
    *,
    run_remote: Optional[RunRemote] = None,
) -> tuple[bool, str]:
    """Verify the A3 container is reachable + has a CANN install.

    Returns (reachable, message).
    """
    if run_remote is None:
        run_remote = _default_run_remote(env_a3_user, env_a3_host, env_a3_container)
    rc, out, err = run_remote("echo PROBE_OK && which bisheng 2>&1 | head -1")
    if rc != 0:
        return False, f"A3 probe failed (rc={rc}): {err.strip() or out.strip()}"
    if "PROBE_OK" not in out:
        return False, f"A3 probe returned unexpected output: {out.strip()[:200]}"
    return True, "A3 reachable"


def _manifest_schema_block(workspace: Path) -> str:
    """Return a best-effort manifest schema block for the CPU truth prompt."""
    manifest_path = workspace / "manifest.json"
    if not manifest_path.is_file():
        return ""
    try:
        manifest = json.loads(manifest_path.read_text())
        return (
            "## Op schema (from manifest.json)\n\n"
            f"Inputs: {manifest.get('inputs', [])}\n\n"
            f"Outputs: {manifest.get('outputs', [])}\n\n"
        )
    except Exception as error:
        logging.getLogger(__name__).debug(
            "Recoverable operation failed.", exc_info=error
        )
        return ""


def _emit_cpu_truth_scaffold(op_dir: Path, workspace: Path) -> Optional[Path]:
    """Phase O2.5 step 0.5 (2026-05-14, apply_adam_w_quant aftermath).

    Emits `workspace/cpu_truth_template.md` — a discovery prompt to the
    kernel-worker that:

    1. Names the canonical algorithm spec (PyTorch / standard math source)
    2. Identifies the op as "needs CPU truth" (when the op is standard math)
    3. Gives a Python skeleton with input/output schema from manifest.json

    Non-fatal: if manifest.json is missing or unreadable, write a generic
    skeleton. The worker is responsible for filling it in during Phase A.5
    (between Phase A source-summary and Phase B file-mirror).

    Without CPU truth, "precision alignment" against A3-NPU-output is
    meaningless when the upstream reference may be buggy. apply_adam_w_quant
    debug session 2026-05-14 burned $26 of probe spawns investigating
    "A3 drops m_old" hypothesis; would have been resolved in 1 CPU-truth
    measurement.

    Returns the path on success, None on failure.
    """
    try:
        op = resolve_logical_op_name(op_dir)
        template = workspace / "cpu_truth_template.md"
        # Skip if already present (kw may have already authored)
        if template.exists() or (workspace / "cpu_truth_reference.py").exists():
            return template if template.exists() else None
        template.write_text(
            _CPU_TRUTH_TEMPLATE.format(
                op=op, schema_block=_manifest_schema_block(workspace)
            )
        )
        return template
    except Exception as e:
        log.info(f"[phase_o25_a3_ref] cpu_truth_scaffold WARN (non-fatal): {e}")
        return None


def _run_prior_art_scan(op_dir: Path, workspace: Path) -> Optional[Path]:
    """Run the bundled prior-art scanner and persist its provenance artifact.

    The scan is advisory and non-fatal: it inventories an upstream arch35
    implementation, shared target implementation, staged workspace candidate,
    or external candidate without replacing the mandatory live arch22 capture.
    """
    try:
        import importlib.util

        scanner_path = (
            Path(__file__).resolve().parents[4]
            / "skills"
            / "aog-prior-art-verify"
            / "scripts"
            / "scan_prior_art.py"
        )
        if not scanner_path.is_file():
            return None
        spec = importlib.util.spec_from_file_location("scan_prior_art", scanner_path)
        if spec is None or spec.loader is None:
            return None
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        result = module.scan(resolve_logical_op_name(op_dir), op_dir, workspace)
        output = module.write_scan_result(workspace, result)
        source_types = ",".join(
            str(source.get("type", ""))
            for source in result.get("sources", [])
            if isinstance(source, dict)
        )
        log.info(
            "[phase_o25_a3_ref] prior-art scan: has_prior_art=%s "
            "trust=%s sources=%d%s",
            result.get("has_prior_art"),
            result.get("highest_trust", "none"),
            len(result.get("sources", [])),
            f" ({source_types})" if source_types else "",
        )
        return output
    except Exception as exc:
        log.info("[phase_o25_a3_ref] prior-art scan WARN (non-fatal): %s", exc)
        return None


def _source_arch_complete_gate(op_dir: Path) -> tuple[bool, str]:
    """Require a deterministically detected arch22 source and fail closed."""
    detection = detect_source_arch(op_dir)
    if detection.supported and detection.arch == "arch22":
        return True, (
            f"arch22 source detected by {detection.method}: "
            f"{', '.join(detection.evidence)}"
        )
    return False, (
        f"unsupported source architecture: arch={detection.arch!r}, "
        f"method={detection.method}, evidence={list(detection.evidence)}"
    )


def _isolated_install_command(
    build_root_q: str, custom_opp_install_path: Optional[str]
) -> str:
    """Return the fail-closed custom OPP installation command, if requested."""
    if custom_opp_install_path is None:
        return ""
    install_path_q = shlex.quote(custom_opp_install_path)
    env_script_q = shlex.quote(
        f"{custom_opp_install_path}/vendors/custom_nn/bin/set_env.bash"
    )
    return (
        f"; custom_pkg={build_root_q}/build_out/"
        f"cann-ops-nn-custom-linux.$(uname -m).run; "
        f"if [[ ! -f \"$custom_pkg\" ]]; then "
        f"  echo 'ORCHESTRATOR: custom-op package missing after source build' >&2; "
        f"  exit 3; "
        f"fi; "
        f"if [[ -e {install_path_q} ]]; then "
        f"  echo 'ORCHESTRATOR: refusing to reuse custom OPP install path' >&2; "
        f"  exit 3; "
        f"fi; "
        f"\"$custom_pkg\" --quiet --install-path={install_path_q} 2>&1; "
        f"if [[ ! -f {env_script_q} ]]; then "
        f"  echo 'ORCHESTRATOR: isolated custom OPP activation script missing' >&2; "
        f"  exit 3; "
        f"fi"
    )


def _build_a3_kernel_command(
    build_root: Path,
    op_dir: Path,
    a3_cann_path: str,
    op_name: str,
    soc: str,
    custom_opp_install_path: Optional[str],
) -> str:
    """Build the remote kernel command with the existing fail-closed checks."""
    build_root_q = shlex.quote(str(build_root))
    cann_path_q = shlex.quote(a3_cann_path)
    missing_build_message_q = shlex.quote(
        f"ORCHESTRATOR: build.sh not at {build_root}/build.sh — "
        f"ops-nn-root discovery failed for {op_dir}"
    )
    return (
        f"set -eo pipefail; "
        f"if [[ ! -f {build_root_q}/build.sh ]]; then "
        f"  printf '%s\\n' {missing_build_message_q} >&2; "
        f"  exit 2; "
        f"fi; "
        f"cd {build_root_q} && "
        f"export ASCEND_HOME_PATH={cann_path_q} && "
        f"source {cann_path_q}/set_env.sh 2>&1 && "
        f"export ASCEND_HOME_PATH={cann_path_q} && "
        f"bash build.sh --pkg --ops={shlex.quote(op_name)} --soc={shlex.quote(soc)} "
        f"2>&1 | tail -30"
        f"{_isolated_install_command(build_root_q, custom_opp_install_path)}"
    )


def build_a3_reference_kernel(
    op_dir: Path,
    a3_cann_path: str,
    *,
    run_remote: RunRemote,
    soc: str = "ascend910b",
    logical_op_name: Optional[str] = None,
    custom_opp_install_path: Optional[str] = None,
) -> tuple[bool, str]:
    """Build the existing A3 kernel package inside the A3 container.

    Assumes the A3 container has `/home` mounted with the user's ops-nn
    checkout visible at the same path inside the container (per
    sliced-container convention, see memory rule).

    Args:
        op_dir: host-side path to ops-nn op dir (e.g.
            ~/workspace/cann/ops-nn/loss/ctc_loss_v3). Used as-is inside
            container because /home is mounted 1:1.
        a3_cann_path: container path to CANN install (e.g.
            /home/npu_user/cann/cann-9.0.0).
        run_remote: injected ssh+docker-exec callable.
        soc: which A3 SoC family to target. Default ascend910b which is
            compatible with both Ascend910_9382 and Ascend910_9392.
        logical_op_name: original op name when ``op_dir`` is a translated
            fixed snapshot path whose manifest is not locally readable.
        custom_opp_install_path: optional absolute, run-scoped directory in
            the A3 container.  When provided, install the generated custom-op
            package there (never into the system OPP tree) and verify its
            ``set_env.bash`` activation script exists.

    Returns:
        (success, log) — success=True if build returns 0 and no "Error"
        line appears in the tail.
    """
    op_name = logical_op_name or resolve_logical_op_name(op_dir)
    if custom_opp_install_path is not None and (
        not custom_opp_install_path.startswith("/")
        or any(ch in custom_opp_install_path for ch in "\x00\r\n")
    ):
        return False, "custom OPP install path must be an absolute single-line path"
    # P124-followup (2026-05-16): build.sh lives at the ops-nn root, NOT
    # inside each op_dir. The `--ops=<op_name>` flag selects the op.
    # Previously this function `cd`'d into op_dir then ran `bash build.sh`
    # which silently failed (file not found, stripped to empty error log).
    # Walk up the path until we find build.sh OR settle on op_dir.parent.parent
    # as the conventional ops-nn root (op_dir = <ops-nn-root>/<category>/<op>).
    build_root = op_dir.parent.parent  # default heuristic: 2 levels up
    cmd = _build_a3_kernel_command(
        build_root,
        op_dir,
        a3_cann_path,
        op_name,
        soc,
        custom_opp_install_path,
    )
    rc, stdout, stderr = run_remote(cmd)
    build_log = stdout + stderr
    if rc != 0:
        return False, build_log
    # Defensive: even with rc=0 the build may have warned. Look for "Error"
    # / "FAILED" patterns in the tail.
    if "Error" in build_log or "FAILED" in build_log or "error: " in build_log.lower():
        return False, build_log
    return True, build_log


def _build_a3_reference_runner_if_present(
    workspace: Path,
    a3_container_workspace_q: str,
    a3_cann_path_q: str,
    *,
    run_remote: RunRemote,
) -> Optional[str]:
    """Build a Path B runner when the workspace includes its build script.

    Path B authors emit ``build_runner.sh`` + ``CMakeLists.txt`` for operators
    without a torch_npu wrapper. Path A workspaces omit the script, making this
    helper a no-op.
    """
    if not (workspace / "build_runner.sh").exists():
        return None

    # 2026-06-13 (owner-debugged): do NOT silence set_env.sh (was
    # `> /dev/null 2>&1`). When the configured A3_CANN_PATH is missing (e.g. a
    # deleted home-copy CANN install), the source fails under `set -e` and —
    # if silenced — aborts rc=1 with EMPTY output, so the error capture below
    # shows only the SSH login banner and the real "No such file" cause is
    # HIDDEN (masqueraded as a mysterious "A3 wall" for days). Keeping stderr
    # makes a missing/broken CANN install diagnosable at a glance.
    build_cmd = (
        # set -o pipefail: the trailing `| tail -30` would otherwise mask
        # build_runner.sh's exit code (pipeline rc = tail's rc = 0), so a
        # genuine compile/link failure (e.g. missing aclnn header for an op
        # not shipped in the A3 CANN) read as rc=0 "build OK" — then the
        # runner found no binary, captured 0 cases, and the failure
        # surfaced two steps downstream as a misleading CAPTURE_INCOMPLETE.
        # pipefail propagates the real rc so build failures fail-loud HERE
        # (and so the P128 build-from-source fallback below actually fires).
        f"set -eo pipefail; "
        f"cd {a3_container_workspace_q} && "
        f"source {a3_cann_path_q}/set_env.sh 2>&1 && "
        f"export ASCEND_HOME_PATH={a3_cann_path_q} && "
        f"bash build_runner.sh 2>&1 | tail -30"
    )
    rc_b, stdout_b, stderr_b = run_remote(build_cmd)
    if rc_b != 0:
        return (
            f"Path B build_runner.sh failed (rc={rc_b}): "
            f"{(stdout_b + stderr_b)[-500:]}"
        )
    return None


def _is_absolute_single_line_path(path: str) -> bool:
    """Return whether a shell path is absolute and cannot inject a new line."""
    return path.startswith("/") and not any(char in path for char in "\x00\r\n")


def _validate_a3_reference_inputs(
    a3_cann_path: str, custom_opp_env_script: Optional[str], npu_id: Optional[int]
) -> Optional[str]:
    """Return the legacy validation error for invalid A3 execution inputs."""
    if not _is_absolute_single_line_path(a3_cann_path):
        return "A3 CANN path must be an absolute single-line path"
    if custom_opp_env_script is not None:
        if not _is_absolute_single_line_path(custom_opp_env_script):
            return "custom OPP env script must be an absolute single-line path"
    if npu_id is None:
        return None
    if isinstance(npu_id, bool) or not isinstance(npu_id, int):
        return "A3 NPU id must be a non-negative integer"
    if npu_id < 0:
        return "A3 NPU id must be a non-negative integer"
    return None


def _a3_reference_workspace_paths(workspace: Path) -> tuple[str, str]:
    """Map a local workspace to the existing A3 host and container paths."""
    host_root = _a3_host_workspace_root_from_env(workspace)
    container_workspace = (
        f"{_a3_container_home()}/workspace/a5_ops_a3_to_a5/workspace/{workspace.name}"
    )
    host_workspace = (
        f"{host_root}/workspace/a5_ops_a3_to_a5/workspace/{workspace.name}"
    )
    return container_workspace, host_workspace


def _ensure_a3_edge_inputs(workspace: Path) -> Optional[str]:
    """Generate missing edge inputs and retry optional local truth providers."""
    edge_inputs = workspace / "edge_inputs.pt"
    if edge_inputs.exists() or not (workspace / "input_gen.py").exists():
        return None
    input_gen_rc = subprocess.call(
        ["python3", "input_gen.py"],
        cwd=str(workspace),
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    if input_gen_rc != 0 or not edge_inputs.exists():
        return f"input_gen.py failed (rc={input_gen_rc}) or did not produce edge_inputs.pt"
    if not (workspace / "native_capture.pt").exists():
        _, native_capture_message = provision_native_capture(workspace)
        log.info(
            "[phase_o25_a3_ref] native_capture retry after input_gen: %s",
            native_capture_message,
        )
    if not (workspace / "cpu_truth_outputs.pt").exists():
        _, cpu_truth_message = provision_cpu_truth(workspace)
        log.info(
            "[phase_o25_a3_ref] cpu_truth retry after input_gen: %s",
            cpu_truth_message,
        )
    return None


def _custom_opp_activation_command(custom_opp_env_script: Optional[str]) -> str:
    """Return the existing fail-closed custom OPP activation fragment."""
    if custom_opp_env_script is None:
        return ""
    custom_env_q = shlex.quote(custom_opp_env_script)
    return (
        f"if [[ ! -f {custom_env_q} ]]; then "
        f"  echo 'ORCHESTRATOR: isolated custom OPP activation script missing' >&2; "
        f"  exit 3; "
        f"fi; "
        f"source {custom_env_q} 2>&1 && "
    )


def _a3_reference_runner_command(
    a3_container_workspace: str,
    a3_cann_path: str,
    runner_script: Path,
    npu_id: Optional[int],
    custom_opp_env_script: Optional[str],
) -> str:
    """Build the bounded-output remote reference-runner command."""
    workspace_q = shlex.quote(a3_container_workspace)
    cann_path_q = shlex.quote(a3_cann_path)
    runner_log_q = shlex.quote(
        f"{a3_container_workspace}/.a3_reference_runner.log"
    )
    runner_path_q = shlex.quote(
        f"{a3_container_workspace}/{runner_script.name}"
    )
    visible_device = (
        f"export ASCEND_RT_VISIBLE_DEVICES={npu_id} && " if npu_id is not None else ""
    )
    failure_pattern_q = shlex.quote(
        "NotImplementedError|could not find an implementation|Could not run|"
        "undefined symbol|561103|no binary|kernel[- ]not[- ]registered|"
        "aclnn[A-Za-z0-9_]*.*(failed|ERROR)"
    )
    return (
        f"set -eo pipefail; "
        f"cd {workspace_q} && "
        f"source {cann_path_q}/set_env.sh 2>&1 && "
        f"export ASCEND_HOME_PATH={cann_path_q} && "
        f"{_custom_opp_activation_command(custom_opp_env_script)}"
        f"{visible_device}"
        f"set +e; "
        f"python3 {runner_path_q} >{runner_log_q} 2>&1; "
        f"runner_rc=$?; "
        f"set -e; "
        f"if [[ \"$runner_rc\" -ne 0 ]]; then "
        f"  grep -E -i -m 8 {failure_pattern_q} {runner_log_q} || true; "
        f"fi; "
        f"tail -50 {runner_log_q}; "
        f"exit \"$runner_rc\""
    )


def run_a3_reference(
    op_dir: Path,
    workspace: Path,
    a3_user: str,
    a3_host: str,
    a3_container: str,
    a3_cann_path: str,
    *,
    runner_script: Path,
    run_remote: RunRemote,
    push_dir: Optional[Callable[[Path, str, str, str], Optional[str]]] = None,
    pull_files: Optional[Callable[[str, str, str, list, Path], Optional[str]]] = None,
    npu_id: Optional[int] = None,
    custom_opp_env_script: Optional[str] = None,
) -> tuple[bool, str]:
    """Stage the per-op aclnn runner inside the container + execute.

    The runner is responsible for:
    - Loading workspace/edge_inputs.pt (already on host; container sees
      it via the slice mount if workspace is under /home/npu_user_*/)
    - Calling the aclnn API for each case
    - Writing workspace/edge_dataset.pt with {inputs, a3_outputs}
    - Writing workspace/a3_baseline_perf.json with per-case timings

    Args:
        op_dir: ops-nn op dir (passes location of built .so)
        workspace: workspace/<op>/ path (contains edge_inputs.pt + runner)
        runner_script: workspace/run_a3_reference.py path on host
        custom_opp_env_script: optional absolute path to the isolated custom
            OPP ``set_env.bash`` created by the source-build fallback.  It is
            sourced only in this runner shell after the base CANN environment.
        ...

    Returns:
        (success, message)
    """
    validation_error = _validate_a3_reference_inputs(
        a3_cann_path, custom_opp_env_script, npu_id
    )
    if validation_error:
        return False, validation_error
    # Container path mapping (2026-05-13 fix): A3 container only mounts
    # `/home/npu_user_<agent>:/home/npu_user` — the a5_ops workspace path
    # `/home/npu_user/workspace/a5/a5_ops/workspace/<op>/` is NOT visible inside
    # the container as-is. Stage the workspace to the slice-mounted tree on
    # A3 host (`/home/npu_user_<agent>/workspace/a5_ops_a3_to_a5/workspace/<op>/`),
    # which the container sees at `/home/npu_user/workspace/a5_ops_a3_to_a5/workspace/<op>/`.
    # After exec, pull the produced artifacts back to local workspace.
    a3_container_workspace, a3_host_workspace = _a3_reference_workspace_paths(workspace)
    if not _is_absolute_single_line_path(a3_container_workspace):
        return False, "A3 container workspace must be an absolute single-line path"
    input_error = _ensure_a3_edge_inputs(workspace)
    if input_error:
        return False, input_error

    # Push local workspace → A3 host (via scp). We push the WHOLE workspace
    # dir so the runner finds run_a3_reference.py + input_gen.py + edge_inputs.pt
    # + manifest.json all at the same relative path.
    _push = push_dir if push_dir is not None else _scp_push_dir
    push_err = _push(workspace, a3_user, a3_host, a3_host_workspace)
    if push_err:
        return False, f"scp push of workspace to A3 failed: {push_err}"

    build_error = _build_a3_reference_runner_if_present(
        workspace,
        shlex.quote(a3_container_workspace),
        shlex.quote(a3_cann_path),
        run_remote=run_remote,
    )
    if build_error:
        return False, build_error

    cmd = _a3_reference_runner_command(
        a3_container_workspace,
        a3_cann_path,
        runner_script,
        npu_id,
        custom_opp_env_script,
    )
    rc, stdout, stderr = run_remote(cmd)
    exec_log = stdout + stderr
    if rc != 0:
        return False, f"runner exited rc={rc}: {_bounded_runner_failure(exec_log)}"

    # Pull produced artifacts back from A3 → local workspace.
    _pull = pull_files if pull_files is not None else _scp_pull_files
    pull_err = _pull(
        a3_user, a3_host, a3_host_workspace,
        ["edge_dataset.pt", "a3_baseline_perf.json"],
        workspace,
    )
    if pull_err:
        return False, f"scp pull of A3 artifacts failed: {pull_err}"

    # Verify the runner produced expected outputs (now local)
    if not (workspace / "edge_dataset.pt").exists():
        return False, f"runner ran but edge_dataset.pt not produced. Log tail:\n{exec_log[-500:]}"
    if not (workspace / "a3_baseline_perf.json").exists():
        return False, f"runner ran but a3_baseline_perf.json not produced. Log tail:\n{exec_log[-500:]}"
    return True, f"A3 ref captured: edge_dataset.pt + a3_baseline_perf.json. Log tail:\n{exec_log[-300:]}"


def _try_a3_author(workspace: Path, op_dir: Path) -> tuple[bool, dict]:
    """Invoke aog-a3-author skill if trigger gate fires.

    Returns (attempted, result_dict). attempted=False means the trigger
    gate refused (wrong mode / runner already present); attempted=True
    means the skill ran (success or failure indicated in result_dict).

    Lives in this module (not in phase_o25_a3_ref.run_a3_reference) so the
    happy path (skill rarely fires when scripts exist) stays cheap.
    """
    try:
        import a3_author_invoke as _aai  # type: ignore
    except Exception:
        # Fallback: a3_author_invoke not importable (test environment etc.)
        return False, {"verdict": "SKILL_MODULE_MISSING", "errors": ["import a3_author_invoke failed"]}

    # Read opgen_mode from workspace state
    state_path = workspace / ".opgen_state.json"
    opgen_mode = ""  # missing/unknown mode fails the trigger closed
    if state_path.exists():
        try:
            opgen_mode = json.loads(state_path.read_text()).get("opgen_mode", "")
            if not isinstance(opgen_mode, str):
                opgen_mode = ""
        except Exception as error:
            logging.getLogger(__name__).debug(
                "Recoverable operation failed.", exc_info=error
            )

    should_fire, _reason = _aai.should_trigger(workspace, opgen_mode)
    if not should_fire:
        return False, {"verdict": "TRIGGER_SKIPPED", "errors": [_reason]}

    result = _aai.author_one(workspace, op_dir, opgen_mode=opgen_mode)
    return True, result


# ---------------------------------------------------------------------------
# scp transport (defaults for run_a3_reference; patch on THIS module in tests)
# ---------------------------------------------------------------------------
def _scp_push_dir(local_dir: Path, a3_user: str, a3_host: str, remote_dir: str) -> Optional[str]:
    """Tar local_dir, scp to A3, extract at remote_dir. Returns None on success
    or error string."""
    import tempfile
    with tempfile.NamedTemporaryFile(suffix=".tar.gz", delete=False) as tf:
        tar_path = Path(tf.name)
    try:
        rc = subprocess.call(
            ["tar", "czf", str(tar_path), "-C", str(local_dir.parent), local_dir.name],
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        )
        if rc != 0:
            return f"tar exited {rc}"
        remote_parent = remote_dir.rsplit("/", 1)[0]
        scp_target = f"{a3_user}@{a3_host}:/tmp/{tar_path.name}"
        rc = subprocess.call(
            ["scp", "-q", "-o", "StrictHostKeyChecking=no",
             "-o", "UserKnownHostsFile=/dev/null",
             str(tar_path), scp_target],
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        )
        if rc != 0:
            return f"scp push exited {rc}"
        # Extract on remote (overwrites)
        rc = subprocess.call(
            ["ssh", "-o", "StrictHostKeyChecking=no",
             "-o", "UserKnownHostsFile=/dev/null",
             f"{a3_user}@{a3_host}",
             f"mkdir -p '{remote_parent}' && rm -rf '{remote_dir}' && "
             f"tar xzf /tmp/{tar_path.name} -C '{remote_parent}' && "
             f"rm -f /tmp/{tar_path.name}"],
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        )
        if rc != 0:
            return f"remote extract exited {rc}"
        return None
    finally:
        tar_path.unlink(missing_ok=True)


def _scp_pull_files(
    a3_user: str, a3_host: str, remote_dir: str,
    filenames: list, local_dir: Path,
) -> Optional[str]:
    """scp each filename from remote_dir/ → local_dir/. Returns None on success
    or error string (only fails on hard ssh/scp error; missing files are
    tolerated since caller's existence check covers them)."""
    for fname in filenames:
        rc = subprocess.call(
            ["scp", "-q", "-o", "StrictHostKeyChecking=no",
             "-o", "UserKnownHostsFile=/dev/null",
             f"{a3_user}@{a3_host}:{remote_dir}/{fname}",
             str(local_dir / fname)],
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        )
        # Don't hard-fail on per-file errors (runner may have produced a
        # subset); caller's .exists() check is the authoritative gate.
        _ = rc
    return None


def format_block_message(op: str, rep: O25A3Report) -> str:
    """Human-readable block message when verdict != READY*."""
    lines = [
        f"[phase_o25_a3_ref] op={op} verdict={rep.verdict}",
    ]
    for err in rep.errors:
        lines.append(f"  ERROR: {err}")
    for rec in rep.recommendations:
        lines.append(f"  → {rec}")
    if rep.peer_op_dependencies:
        lines.append(
            f"  NOTE: this op depends on peer op(s): "
            f"{', '.join(rep.peer_op_dependencies)}. "
            f"Cross-op router edits may be required (see KB W9)."
        )
    return "\n".join(lines)
